// app/api/debug/route.ts
export async function GET() {
  return Response.json({
    NODE_ENV: process.env.NODE_ENV,
    API_DOMAIN: process.env.API_DOMAIN,
    APP_NAME: process.env.APP_NAME,
    NEXT_PUBLIC_LIFF_ID: process.env.NEXT_PUBLIC_LIFF_ID,
    DATABASE_URL:process.env.DATABASE_URL,
    LINE_MESSAGING_ACCESS_TOKEN:process.env.LINE_MESSAGING_ACCESS_TOKEN,
    BASE_PATH:process.env.BASE_PATH,
    LINE_DATA_MESSAGING_API:process.env.LINE_DATA_MESSAGING_API,
    LINE_ENDPOINT_API_VERIFY:process.env.LINE_ENDPOINT_API_VERIFY,
    LINE_LIFF_CHANNEL_ID:process.env.LINE_LIFF_CHANNEL_ID,
    LINE_MESSAGING_API:process.env.LINE_MESSAGING_API,
    LINE_MESSAGING_CHANNEL_ID:process.env.LINE_MESSAGING_CHANNEL_ID,
    LINE_MESSAGING_CHANNEL_SECRET:process.env.LINE_MESSAGING_CHANNEL_SECRET,
    LINE_MESSAGING_OAUTH_ISSUE_TOKENV2:process.env.LINE_MESSAGING_OAUTH_ISSUE_TOKENV2,
    LINE_MESSAGING_OAUTH_ISSUE_TOKENV3:process.env.LINE_MESSAGING_OAUTH_ISSUE_TOKENV3,
    SOCKET_IO_SERVER:process.env.SOCKET_IO_SERVER,
    NEXT_PUBLIC_SOCKET_IO_SERVER:process.env.NEXT_PUBLIC_SOCKET_IO_SERVER
  })
}
