# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Create .env.production
      run: |
        cat <<EOF > .env.production
        APP_NAME=${{ secrets.APP_NAME }}
        NODE_ENV=${{ secrets.NODE_ENV }}
        API_DOMAIN=${{ secrets.API_DOMAIN }}
        BASE_PATH=${{ secrets.BASE_PATH }}
        LINE_MESSAGING_ACCESS_TOKEN=${{ secrets.LINE_MESSAGING_ACCESS_TOKEN }}
        NEXT_PUBLIC_LIFF_ID=${{secrets.NEXT_PUBLIC_LIFF_ID}}
        DATABASE_URL=${{secrets.DATABASE_URL}}
        LINE_DATA_MESSAGING_API=${{secrets.LINE_DATA_MESSAGING_API}}
        LINE_ENDPOINT_API_VERIFY=${{secrets.LINE_ENDPOINT_API_VERIFY}}
        LINE_LIFF_CHANNEL_ID=${{secrets.LINE_LIFF_CHANNEL_ID}}
        LINE_MESSAGING_API=${{secrets.LINE_MESSAGING_API}}
        LINE_MESSAGING_CHANNEL_ID=${{secrets.LINE_MESSAGING_CHANNEL_ID}}
        LINE_MESSAGING_CHANNEL_SECRET=${{secrets.LINE_MESSAGING_CHANNEL_SECRET}}
        LINE_MESSAGING_OAUTH_ISSUE_TOKENV2=${{secrets.LINE_MESSAGING_OAUTH_ISSUE_TOKENV2}}
        LINE_MESSAGING_OAUTH_ISSUE_TOKENV3=${{secrets.LINE_MESSAGING_OAUTH_ISSUE_TOKENV3}}
        SOCKET_IO_SERVER=${{secrets.SOCKET_IO_SERVER}}
        EOF

    - name: my-step
      run: echo "Hello World!!"

    - name: Build app
      run: npm run build --if-present

    - name: Reload PM2
      run: pm2 reload mwa-km-dt2025

#    - name: Reload NGROK
#      run: pm2 reload ngrok-tunnel


